apiVersion: cluster.appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics-cluster-agent-sai-narasingu
spec:
  appName: "nodejsappsailocal"
  controllerUrl: "https://controllerces.saas.appdynamics.com:443"
  account: "controllerces"
  # docker image info
  image: "docker.io/appdynamics/cluster-agent:22.4.0"
  serviceAccountName: appdynamics-cluster-agent
  nsToMonitor: [sai-narasingu]
  resourcesToInstrument: [Deployment]
  netvizInfo:
    bciEnabled: true
  stdoutLogging: "true"
  logLevel: "DEBUG"
  metricUploadRetryCount: 3
  metricUploadRetryIntervalMilliSeconds: 5
  numberOfTaskWorkers: 2
  instrumentationMethod:  Env
  nsToInstrumentRegex: sai-narasingu
  instrumentationRules:
    - appName: Nodejs-Sai-Cluster-Agent
      language: nodejs
      imageInfo:
        image: "docker.io/appdynamics/nodejs-agent:21.9.0-14-alpine"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: Always
  resources:
    limits:
      cpu: 300m
      memory: "200Mi"
    requests:
      cpu: 200m
      memory: "100Mi"
